# This file was generated by GoReleaser. DO NOT EDIT.
cask "tnnl" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6949ddad12d6cc586c34412e9e06e8029499be93b80eab20efb9bd39bb6d4114"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f81706e000c3273f4ae124efeac060e6940cfad916f785b92a675debd74e81dc"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79495a83a0292cd8cd218ac0b5978bb7c0ee7c84332e37a56ee1febbe0409bfd"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "710edf0467eeeb9377e30f146fda8baba103d400d0c79dba7fcfe80b54761842"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_linux_arm64.tar.gz"
    end
  end

  name "tnnl"
  desc "Share local HTTP services via public HTTPS URLs"
  homepage "https://tnnl.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tnnl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tnnl"]
    end
  end

  # No zap stanza required

end
