# This file was generated by GoReleaser. DO NOT EDIT.
cask "tnnl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "75ef34faa9cbc37701532b8e261fda437e3013531a1124ab09c28f1dbd7ec42e"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f42d92b9934329b22ebb4d180c49cb7cb9c0127a7f1695ee0eaa3b93d1dd458"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46a3a2772cfbfc211c11ec6cce7cbfafa54dc0ea7ab8b9fcb909a69c862c0549"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "393b465b6bbd9816f74f1a6ef82f83e4eef2e5ab4b2c892efc0e280d3903a405"
      url "https://github.com/tnnl-sh/cli/releases/download/v#{version}/tnnl_linux_arm64.tar.gz"
    end
  end

  name "tnnl"
  desc "Share local HTTP services via public HTTPS URLs"
  homepage "https://tnnl.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tnnl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tnnl"]
    end
  end

  # No zap stanza required

end
