# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tnnl < Formula
  desc "Share local HTTP services via public HTTPS URLs"
  homepage "https://tnnl.sh"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tnnl-sh/cli/releases/download/v0.0.0/tnnl_darwin_amd64.tar.gz"
      sha256 "4761d7d5a9aee77d3155f722fcc23cefc6bcc9173a529d48eff12acb1f8f2664"

      define_method(:install) do
        bin.install "tnnl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tnnl-sh/cli/releases/download/v0.0.0/tnnl_darwin_arm64.tar.gz"
      sha256 "61c9037cc1a3e3be980787a087e8ddab6ce3a78086f6d5861bebee972d9c21de"

      define_method(:install) do
        bin.install "tnnl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tnnl-sh/cli/releases/download/v0.0.0/tnnl_linux_amd64.tar.gz"
      sha256 "3d98910672aa2adeb5626bdd258220e6c3bc4c644738b19b78d12b8740d059ca"
      define_method(:install) do
        bin.install "tnnl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tnnl-sh/cli/releases/download/v0.0.0/tnnl_linux_arm64.tar.gz"
      sha256 "4e1df3837b6dbf67049d7d3d8dfbdc06e53537df87f2f0fb80f1037e9c19da7e"
      define_method(:install) do
        bin.install "tnnl"
      end
    end
  end

  test do
    system "#{bin}/tnnl", "version"
  end
end
